baseURL = "https://jvlcodex.netlify.app/"
title = "JVL Codex"

[params]
    mainurl = "https://jvlcodex.netlify.app"

[menu]
  [[menu.main]]
    identifier = "Archive"
    name = "Archive"
    url = "/posts"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 20

[taxonomies]
  category = "categories"
  tag = "tags"

[markup.highlight]
      codeFences = true
      guessSyntax = true
      hl_Lines = ""
      lineNoStart = 1
      lineNos = false
      lineNumbersInTable = true
      tabWidth = 4
      noClasses = false
      style = "solarized"
      pygmentsUseClasses = true
      pygmentsCodefences = true
